name: "Build and deploy"

on:
  pull_request:
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  call:
    name: "CI"
    uses: "delphai/.github/.github/workflows/callable-k8s-build-deploy.yaml@master"
    secrets: inherit
