name: "Remove from review cluster"

on: [delete]

jobs:
  destroy-review:
    name: "Remove branch build"

    runs-on: ubuntu-latest

    steps:
      - name: Make slug variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Load Actions config
        id: config
        uses: yumemi-inc/action-config@v0.1.0
        with:
          repository: "delphai/.github"
          github-token: ${{ secrets.DEVOPS_BOT_GITHUB_TOKEN }}
          mask-variables: false

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Login to AKS
        run: az aks get-credentials ${{ steps.config.outputs.AKS_GET_CREDENTIALS_REVIEW }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.10.1"

      - name: Generate Helm deployment name
        run: |
          # Use `_SLUG_URL` variants to pass Helm validation

          DEPLOYMENT_NAME="$GITHUB_REPOSITORY_NAME_PART_SLUG_URL-$GITHUB_EVENT_REF_SLUG_URL"

          # Ensure name length https://github.com/helm/helm/issues/6006#issuecomment-553184466
          HELM_MAX_DEPLOYMENT_NAME_LENGTH=53_
          if [ "${#DEPLOYMENT_NAME}" -gt "$HELM_MAX_DEPLOYMENT_NAME_LENGTH" ]; then
              DEPLOYMENT_NAME="$(echo "$DEPLOYMENT_NAME" | cut --characters -44)-$(echo "$DEPLOYMENT_NAME" | md5sum | cut --characters -8)"
          fi

          echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV

      - run: |
          helm uninstall --namespace "$GITHUB_REPOSITORY_NAME_PART_SLUG_URL" "$DEPLOYMENT_NAME" || true
