name: "Remove from review cluster"

on: [delete]

jobs:
  destroy-review:
    name: "Remove branch build"

    runs-on: ubuntu-latest

    steps:
      - name: Make slug variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Login to AKS
        run: az aks get-credentials ${{ vars.AKS_GET_CREDENTIALS_REVIEW }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.10.1"

      - name: Generate Helm release name
        run: |
          # Use `_SLUG_URL` variants to pass Helm validation

          RELEASE_NAME="$GITHUB_REPOSITORY_NAME_PART_SLUG_URL"
          if [ "$GITHUB_EVENT_REF" != "${{ github.event.repository.default_branch }}" ]
          then
            RELEASE_NAME="$RELEASE_NAME-${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
          fi

          # Ensure name length https://github.com/helm/helm/issues/6006#issuecomment-553184466
          HELM_MAX_RELEASE_NAME_LENGTH=53
          if [ "${#RELEASE_NAME}" -gt "$HELM_MAX_RELEASE_NAME_LENGTH" ]; then
              RELEASE_NAME="$(echo "$RELEASE_NAME" | cut --characters -44)-$(echo "$RELEASE_NAME" | md5sum | cut --characters -8)"
          fi

          echo "RELEASE_NAME=$RELEASE_NAME" >> "$GITHUB_ENV"

      - run: |
          helm uninstall --namespace "$GITHUB_REPOSITORY_NAME_PART_SLUG_URL" "$RELEASE_NAME" || true
